AREA: 813,148,885,148,76,1056,1771,1069
RTSP: rtsp://192.168.1.20/playback7.mp4
POST: http://192.168.1.19:8080/v1/app/interface/uploadEvent
POINT: 10.17.1.20
OM: weights/highway-sim.om
EX: weights/ckpt.om
NAME: data/highway.names

MODEL_WIDTH: 608
MODEL_HEIGHT: 608
NMS_THRESHOLD_CONST: 0.65
CLASS_SCORE_CONST: 0.4

# deepsort
MAX_DIST: 0.2
MIN_CONFIDENCE: 0.3
NMS_MAX_OVERLAP: 0.5
MAX_IOU_DISTANCE: 0.7
MAX_AGE: 70
N_INIT: 3
NN_BUDGET: 100